<html>
 <head></head>
 <body>
  <p>Вашей программе будет доступна функция <b>foo</b><b></b>, которая может бросать исключения.<br></p>
  <p>Вам необходимо написать код, который запускает эту функцию, затем ловит исключения <b>ArithmeticError, AssertionError, </b><b>ZeroDivisionError</b> и выводит имя пойманного исключения.</p>
  <p>Пример решения, которое вы должны отправить на проверку.<br></p>
  <pre><code class="language-python">try:
    foo()
except Exception:
    print("Exception")
except BaseException:
    print("BaseException")</code></pre>
  <b><pre></pre></b>
  <div>
   Подсказка: 
   <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy" rel="nofollow noopener noreferrer">https://docs.python.org/3/library/exceptions.html#exception-hierarchy</a>
  </div>
 </body>
</html><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 2 seconds</font><br><br>