<html>
 <head></head>
 <body>
  Вам дано описание наследования классов исключений в следующем формате. 
  <br>
  <b>&lt;имя исключения 1&gt; : &lt;имя исключения 2&gt; &lt;имя исключения 3&gt; ... &lt;имя исключения k</b>&gt;
  <br>Это означает, что 
  <b>исключение 1</b> наследуется от 
  <b>исключения 2</b>, 
  <b>исключения 3</b>, и т. д.
  <div>
   <br>
  </div>
  <div>
   Или эквивалентно записи:
   <div>
    <div>
     <pre><code class="language-python">class Error1(Error2, Error3 ... ErrorK):
    pass</code></pre>
     <br>
     <p>Антон написал код, который выглядит следующим образом.<br></p>
     <pre><code class="language-python">try:
   foo()
except &lt;имя 1&gt;:
   print("&lt;имя 1&gt;")
except &lt;имя 2&gt;:
   print("&lt;имя 2&gt;")
...</code></pre>
     <p>Костя посмотрел на этот код и указал Антону на то, что некоторые исключения можно не ловить, так как ранее в коде будет пойман их предок. Но Антон не помнит какие исключения наследуются от каких. Помогите ему выйти из неловкого положения и напишите программу, которая будет определять обработку каких исключений можно удалить из кода.</p>
     <div>
      <b><b>Важное примечание:</b></b>
     </div>
     <div></div>
     <div>
      В отличие от предыдущей задачи, типы исключений не созданы.
      <br>
     </div>
     <div>
      Создавать классы исключений также не требуется
     </div>
     <div>
      Мы просим вас промоделировать этот процесс, и понять какие из исключений можно и не ловить, потому что мы уже ранее где-то поймали их предка.
     </div>
     <br>
     <h2 style="text-align: center;">Формат входных данных</h2>
     <p>В первой строке входных данных содержится целое число <b>n</b> <b></b>- число классов <b>исключений</b>.<br></p>
     <p>В следующих <b>n</b> строках содержится описание наследования классов. В <b>i-</b>й строке указано от каких классов наследуется <b>i-</b>й класс. Обратите внимание, что класс может ни от кого не наследоваться. Гарантируется, что класс не наследуется сам от себя (прямо или косвенно), что класс не наследуется явно от одного класса более одного раза.</p>
     <p>В следующей строке содержится число <b>m</b> - количество обрабатываемых исключений.<br>Следующие <b>m</b> строк содержат имена исключений в том порядке, в каком они были написаны у Антона в коде.<br>Гарантируется, что никакое исключение не обрабатывается дважды.</p>
     <h2 style="text-align: center;">Формат выходных данных</h2>
     <p>Выведите в отдельной строке имя каждого исключения, обработку которого можно удалить из кода, не изменив при этом поведение программы. Имена следует выводить в том же порядке, в котором они идут во входных данных.<br></p>
     <h2 style="text-align: center;"><b>Пример теста 1</b></h2>
     <p>Рассмотрим код</p>
     <pre><pre><code class="language-python">try:
   foo()
except ZeroDivision :
   print("ZeroDivision")
except OSError:
   print("OSError")
except ArithmeticError:
   print("ArithmeticError")
except FileNotFoundError:
   print("FileNotFoundError")


...</code></pre>

</pre>По условию этого теста, Костя посмотрел на этот код, и сказал Антону, что исключение FileNotFoundError можно не ловить, ведь мы уже ловим OSError -- предок FileNotFoundError
     <br>
    </div>
   </div>
  </div>
 </body>
</html><br><b>Sample Input:</b><br><pre><code class="language-no-highlight">4<br>ArithmeticError<br>ZeroDivisionError : ArithmeticError<br>OSError<br>FileNotFoundError : OSError<br>4<br>ZeroDivisionError<br>OSError<br>ArithmeticError<br>FileNotFoundError<br></code></pre><br><b>Sample Output:</b><br><pre><code class="language-no-highlight">FileNotFoundError</code></pre><br><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 2 seconds</font><br><br>